### ISSUE TITLE
trying to write booking_id -1 in staging

### ISSUE THREAD

**Issue by colincadams** [Recidiviz/recidiviz-data#1071]
```
Exception on /scraper/work [POST]
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1236, in _execute_context
    cursor, statement, parameters, context
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
psycopg2.IntegrityError: insert or update on table "bond" violates foreign key constraint "bond_booking_id_fkey"
DETAIL:  Key (booking_id)=(-1) is not present in table "booking".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/recidiviz/ingest/scrape/worker.py", line 102, in work
    result = scraper_task(params)
  File "/app/recidiviz/ingest/scrape/base_scraper.py", line 237, in _generic_scrape
    scraped_data.ingest_info), metadata)
  File "/app/recidiviz/persistence/persistence.py", line 167, in write
    database.write_people(session, people, metadata)
  File "/app/recidiviz/persistence/database/database.py", line 155, in write_people
    metadata)
  File "/app/recidiviz/persistence/database/database.py", line 186, in _save_record_trees
    session.flush()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2446, in flush
    self._flush(objects)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2584, in _flush
    transaction.rollback(_capture_exception=True)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 67, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 277, in reraise
    raise value
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2544, in _flush
    flush_context.execute()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 416, in execute
    rec.execute(self)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 583, in execute
    uow,
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1116, in _emit_insert_statements
    statement, params
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 980, in execute
    return meth(self, multiparams, params)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 273, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1099, in _execute_clauseelement
    distilled_params,
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1240, in _execute_context
    e, statement, parameters, cursor, context
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1458, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 276, in reraise
    raise value.with_traceback(tb)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1236, in _execute_context
    cursor, statement, parameters, context
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) insert or update on table "bond" violates foreign key constraint "bond_booking_id_fkey"
DETAIL:  Key (booking_id)=(-1) is not present in table "booking".
 [SQL: 'INSERT INTO bond (external_id, amount_dollars, bond_type, bond_type_raw_text, status, status_raw_text, bond_agent, booking_id) VALUES (%(external_id)s, %(amount_dollars)s, %(bond_type)s, %(bond_type_raw_text)s, %(status)s, %(status_raw_text)s, %(bond_agent)s, %(booking_id)s) RETURNING bond.bond_id'] [parameters: {'external_id': None, 'amount_dollars': 450000, 'bond_type': 'CASH', 'bond_type_raw_text': None, 'status': 'INFERRED_SET', 'status_raw_text': None, 'bond_agent': None, 'booking_id': -1}] (Background on this error at: http://sqlalche.me/e/gkpj)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/recidiviz/utils/auth.py", line 98, in auth_and_call
    return func(*args, **kwargs)
  File "/app/recidiviz/ingest/scrape/worker.py", line 109, in work
    raise RequestProcessingError(region, task, params)
recidiviz.ingest.scrape.worker.RequestProcessingError: Error when running '_generic_scrape' for 'us_fl_alachua' with request:
{'ingest_info': None,
 'next_task': {'content': None,
               'cookies': {},
               'custom': {'Booking Date': '11/28/2018'},
               'endpoint': 'http://oldweb.circuit8.org/cgi-bin/jaildetail.cgi?bookno=ASO18JBN007414',
               'headers': None,
               'json': None,
               'params': None,
               'post_data': None,
               'response_type': 'html',
               'task_type': 2},
 'scrape_type': 'background',
 'scraper_start_time': '2019-02-22T20:21:30.414397'}
```

**Comment by zdg2102** [comment]
Fixed with #1119
