### ISSUE TITLE
us_fl_orange broken in staging

### ISSUE THREAD

**Issue by terinpw** [Recidiviz/recidiviz-data#1130]
https://pantheon.corp.google.com/errors/CLrMkoiuxd7EvAE?time=PT6H&project=recidiviz-staging

```Traceback (most recent call last):
  File "/app/recidiviz/ingest/scrape/worker.py", line 102, in work
    result = scraper_task(params)
  File "/app/recidiviz/ingest/scrape/base_scraper.py", line 192, in _generic_scrape
    content, task, request.ingest_info or IngestInfo())
  File "/app/recidiviz/ingest/scrape/regions/us_fl_orange/us_fl_orange_scraper.py", line 46, in populate_data
    person = scraper_utils.one('person', ingest_info)
  File "/app/recidiviz/ingest/scrape/scraper_utils.py", line 85, in one
    return _one(ingest_object, parent)
  File "/app/recidiviz/ingest/scrape/scraper_utils.py", line 63, in _one
    'expected'.format(ingest_object))
ValueError: IngestInfo did not have exactly one person as expected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/recidiviz/utils/auth.py", line 98, in auth_and_call
    return func(*args, **kwargs)
  File "/app/recidiviz/ingest/scrape/worker.py", line 109, in work
    raise RequestProcessingError(region, task, params)
```

**Comment by jamwalla** [comment]
I couldn't reproduce this locally using `run_scraper`, saw some of the same people as in the logs so this might be intermittent. I wonder if it'd be worth/possible to log `content` when the scraper raises an error?

**Comment by jamwalla** [comment]
ohhhh, sorry this is because the site needs cookies!
