### ISSUE TITLE
Improve Vermont error response handling

### ISSUE THREAD

**Issue by jessex** [Recidiviz/recidiviz-data#145]
The good news is that the JailTracker system has reasonable error response bodies when you run into issues. But we aren't making ideal use of them. One example run into by @ageiduschek is that if you accidentally provoke an error from running over an acceptable request rate, you get a fairly unhelpful stacktrace like so:
```
Traceback (most recent call last):
  File "/Users/clementinejacoby/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/Users/clementinejacoby/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/Users/clementinejacoby/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/Users/clementinejacoby/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/Users/clementinejacoby/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/Users/clementinejacoby/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/Users/clementinejacoby/Documents/projects/recidiviz-data/recidiviz/utils/auth.py", line 110, in auth_and_call
    return func(request_handler, *args, **kwargs)
  File "/Users/clementinejacoby/Documents/projects/recidiviz-data/recidiviz/ingest/worker.py", line 90, in post
    result = scraper_task(params)
  File "/Users/clementinejacoby/Documents/projects/recidiviz-data/recidiviz/ingest/us_vt/us_vt_scraper.py", line 277, in scrape_charges
    params['cases'], charges)
  File "/Users/clementinejacoby/Documents/projects/recidiviz-data/recidiviz/ingest/us_vt/us_vt_scraper.py", line 541, in store_record
    agencies = UsVtScraper.extract_agencies(person_data['data'],
KeyError: 'data'
```

This is because the error response doesn't include that key, but we keep trying to process as though it will after making the request that received the error. We should audit and update the various Vermont scrape methods to ensure they handle error responses appropriately and trigger task retry as per convention.

**Comment by ohinds** [comment]
Fixed in #978
