### ISSUE TITLE
Brooks Jeffrey should support decimal bond amounts.

### ISSUE THREAD

**Issue by ohinds** [Recidiviz/recidiviz-data#1497]
Traceback (most recent call last):
  File "/app/recidiviz/ingest/scrape/base_scraper.py", line 203, in _generic_scrape
    content, task, request.ingest_info or IngestInfo())
  File "/app/recidiviz/ingest/scrape/vendors/brooks_jeffrey/brooks_jeffrey_scraper.py", line 69, in populate_data
    booking, split_bonds, bond_status, charge_status, bond_type)
  File "/app/recidiviz/ingest/scrape/vendors/brooks_jeffrey/brooks_jeffrey_scraper.py", line 171, in _split_charges
    total_bond_amount = str(sum(int(bond) for bond in split_bond_amounts))
  File "/app/recidiviz/ingest/scrape/vendors/brooks_jeffrey/brooks_jeffrey_scraper.py", line 171, in <genexpr>
    total_bond_amount = str(sum(int(bond) for bond in split_bond_amounts))
ValueError: invalid literal for int() with base 10: '404.5'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/recidiviz/ingest/scrape/worker.py", line 124, in work
    scraper_task(params)
  File "/app/recidiviz/ingest/scrape/base_scraper.py", line 276, in _generic_scrape
    raise e
  File "/app/recidiviz/ingest/scrape/base_scraper.py", line 205, in _generic_scrape
    raise ScraperPopulateDataError(str(e)) from e
recidiviz.ingest.scrape.errors.ScraperPopulateDataError: invalid literal for int() with base 10: '404.5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/recidiviz/utils/auth.py", line 98, in auth_and_call
    return func(*args, **kwargs)
  File "/app/recidiviz/ingest/scrape/worker.py", line 127, in work
    raise RequestProcessingError(region, task, params)
recidiviz.ingest.scrape.worker.RequestProcessingError: Error when running '_generic_scrape' for 'us_al_autauga' with request:
{'ingest_info': None,
 'next_task': {'content': None,
               'cookies': {'PHPSESSID': '1d20d16a1280811292929106663f7304'},
               'custom': {},
               'endpoint': 'https://www.autaugasheriff.org/roster_view.php?booking_num=1436',
               'headers': None,
               'json': None,
               'params': None,
               'post_data': None,
               'response_type': 'html',
               'task_type': 2},
 'scrape_type': 'background',
 'scraper_start_time': '2019-03-26T02:00:12.749172'}

**Comment by jamwalla** [comment]
fixed in #1501
