### ISSUE TITLE
Intermittent 503 Service Unavailable received from google-cloud-logging

### ISSUE THREAD

**Issue by colincadams** [Recidiviz/recidiviz-data#474]
Looks like other users are seeing the same issue:
https://github.com/googleapis/google-cloud-python/issues/6645

Sample Trace:
```
Traceback (most recent call last):
  File "/env/lib/python3.7/site-packages/google/cloud/logging/handlers/transports/background_thread.py", line 122, in _safely_commit_batch
    batch.commit()
  File "/env/lib/python3.7/site-packages/google/cloud/logging/logger.py", line 383, in commit
    client.logging_api.write_entries(entries, **kwargs)
  File "/env/lib/python3.7/site-packages/google/cloud/logging/_gapic.py", line 131, in write_entries
    partial_success=partial_success,
  File "/env/lib/python3.7/site-packages/google/cloud/logging_v2/gapic/logging_service_v2_client.py", line 399, in write_log_entries
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/env/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/env/lib/python3.7/site-packages/google/api_core/retry.py", line 270, in retry_wrapped_func
    on_error=on_error,
  File "/env/lib/python3.7/site-packages/google/api_core/retry.py", line 179, in retry_target
    return target()
  File "/env/lib/python3.7/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/env/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.ServiceUnavailable: 503 OS Error
```

**Comment by arian487** [comment]
Has this been happening since we moved to appengine flex?

**Comment by colincadams** [comment]
Haven't seen it recently. I don't think that's due to the migration to appengine flex and it seems like the logging client bug is likely still there, but instead probably just that the logging service has been up consistently recently. A lot of people were seeing this issue right when we were seeing it, and there hasn't been much activity since.

I'll close this now and re-open if we see it happening again frequently.
