### ISSUE TITLE
us_ny_scraper: list index out of range

### ISSUE THREAD

**Issue by colincadams** [Recidiviz/recidiviz-data#482]
```
Traceback (most recent call last):
  File "/env/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/recidiviz/utils/auth.py", line 98, in auth_and_call
    return func(*args, **kwargs)
  File "/srv/recidiviz/ingest/worker.py", line 89, in work
    result = scraper_task(params)
  File "/srv/recidiviz/ingest/base_scraper.py", line 157, in _generic_scrape
    ingest_info = self.populate_data(content, params, ingest_info)
  File "/srv/recidiviz/ingest/us_ny/us_ny_scraper.py", line 303, in populate_data
    '//*[@headers="t1l"]')[0].text.split()[0]
IndexError: list index out of range
```

**Comment by jessex** [comment]
>`//*[@headers="t1l"]')[0].text.split()[0]`

I see this all the time in HTML parsing code--in our codebase and elsewhere--where we assume that some selector will return results, index into the results, and then make a call on the expected object in one unbroken chain. I frequently comment on that when I see it in code reviews, e.g. "Are we positive that's going to return a result?" because bugs like this seem like the inevitable result to me. Even if it's more verbose to break that chain out into several calls with checks, I think the safety is worth it. Plus, I imagine we could come up with a thin "library" of basic constructs for safely navigating through the results of selectors and such.
