### ISSUE TITLE
Null value for bond status in `us_co_mesa`

### ISSUE THREAD

**Issue by colincadams** [Recidiviz/recidiviz-data#529]
This issue needs to be fixed so that `us_co_mesa` actually sets the bond value. But we also should have unit tests catch these constraints, either by baking them into the converter or using a fake database layer.

## Details

for `us_co_mesa`

```
Traceback (most recent call last):
  File "/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
psycopg2.IntegrityError: null value in column "status" violates not-null constraint
DETAIL:  Failing row contains (870, 24136265335696_GENERATE, null, NO_BOND, null, null, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/env/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/recidiviz/utils/auth.py", line 98, in auth_and_call
    return func(*args, **kwargs)
  File "/srv/recidiviz/ingest/worker.py", line 89, in work
    result = scraper_task(params)
  File "/srv/recidiviz/ingest/base_scraper.py", line 189, in _generic_scrape
    ingest_info), metadata)
  File "/srv/recidiviz/persistence/persistence.py", line 115, in write
    session.commit()
  File "/env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 954, in commit
    self.transaction.commit()
  File "/env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2313, in flush
    self._flush(objects)
  File "/env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2440, in _flush
    transaction.rollback(_capture_exception=True)
  File "/env/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2404, in _flush
    flush_context.execute()
  File "/env/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 395, in execute
    rec.execute(self)
  File "/env/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 560, in execute
    uow
  File "/env/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/env/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 872, in _emit_insert_statements
    execute(statement, params)
  File "/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/env/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) null value in column "status" violates not-null constraint
DETAIL:  Failing row contains (870, 24136265335696_GENERATE, null, NO_BOND, null, null, null).
 [SQL: 'INSERT INTO bond (external_id, amount_dollars, bond_type, bond_type_raw_text, status, status_raw_text) VALUES (%(external_id)s, %(amount_dollars)s, %(bond_type)s, %(bond_type_raw_text)s, %(status)s, %(status_raw_text)s) RETURNING bond.bond_id'] [parameters: {'external_id': '24136265335696_GENERATE', 'amount_dollars': None, 'bond_type': 'NO_BOND', 'bond_type_raw_text': None, 'status': None, 'status_raw_text': None}] (Background on this error at: http://sqlalche.me/e/gkpj)
```

**Comment by colincadams** [comment]
Filed #530 for catching issues like this in a unit test.

**Comment by arian487** [comment]
Fixed
