### ISSUE TITLE
us_nc_guilford: cannot normalize none / empty string

### ISSUE THREAD

**Issue by colincadams** [Recidiviz/recidiviz-data#838]
https://pantheon.corp.google.com/errors/CJGHt4SIrNS91gE?time=P1D&project=recidiviz-123

Ex.
```
Traceback (most recent call last):
  File "/app/recidiviz/ingest/worker.py", line 102, in work
    result = scraper_task(params)
  File "/app/recidiviz/ingest/base_scraper.py", line 230, in _generic_scrape
    self.get_enum_overrides())
  File "<attrs generated init 29918559f350a995ef307893904210753ef5fe7e>", line 6, in __init__
    _inst_dict['enum_overrides'] = __attr_converter_enum_overrides(enum_overrides)
  File "/app/recidiviz/common/ingest_metadata.py", line 29, in _normalize_keys
    return {normalize(k): v for k, v in dictionary.items()}
  File "/app/recidiviz/common/ingest_metadata.py", line 29, in <dictcomp>
    return {normalize(k): v for k, v in dictionary.items()}
  File "/app/recidiviz/common/common_utils.py", line 36, in normalize
    raise ValueError('Cannot normalize None or empty/whitespace string')
ValueError: Cannot normalize None or empty/whitespace string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/recidiviz/utils/auth.py", line 98, in auth_and_call
    return func(*args, **kwargs)
  File "/app/recidiviz/ingest/worker.py", line 109, in work
    raise RequestProcessingError(region, task, params)
recidiviz.ingest.worker.RequestProcessingError: Error when running '_generic_scrape' for 'us_nc_guilford' with request:
{'ingest_info': None,
 'next_task': {'content': None,
               'cookies': {'ASP.NET_SessionId': 'vn1qyzyldsr3rkod4ogdbnqg'},
               'custom': {},
               'endpoint': 'http://p2c.guilfordcountysheriff.com/jailinmates.aspx',
               'headers': None,
               'json': None,
               'post_data': {'__EVENTVALIDATION': '/wEdABkLUQtSBOp5tUXEnFRMORw59FiaSriqF/5uCJG8XBb9h5zdObrOl2sY04oKRakIOJhZv40pKnbcPP0ZtNgplSLvZawbRo8jy0HQs03+r7fCs7MaBbL8lDAk3VUXqULGUvKesAfKWQ7invFbplHooMHhhBH8BEFP2gmfqQKYnq1e6dne0Xc4O67r7paPwzhgYtHmw34puV0e/td4YjDXQ9Vl0l1zgb3RG1gFN3lrYyAy+qFHTVvBzW8GUqndGj/NCBaVtvBCDwLivoe2C3npPlPQ7Bz/CwNAsxEXDjqf0/DTWtfCJvfN8kI29Vu9mnxRnfpbkAn+0zJCZhPYlcK7gmgCqu0EJoV9xJZeDFSyF9KeS3rruS6dnctiO82CwJHy1iabWaW/M11SCEV+2/hK9NQn3A4icBGSkbD6sA6d1/MurPIvtjsQZ/kceQZHX075zMqL/wCV2Vh7fO8JFDrtfQcjaYYkvmYbrNy7nuPq0v+ZxD3F0/VJS7yJPNH93dlLtK3lLGxG3qGi3HgzEKFootFGANGK8fph2LDl+9e6uB4Gss2BMhpC6cC029GWPgYag3E=',
                             '__VIEWSTATE': '/wEPDwUKMTMyNTg1OTUwMQ9kFgJmD2QWAmYPZBYGZg9kFgICBQ9kFgRmDxYCHgRUZXh0BUU8c2NyaXB0IHNyYz0ianMvanF1ZXJ5LTEuOC4zLm1pbi5qcyIgdHlwZT0idGV4dC9qYXZhc2NyaXB0Ij48L3NjcmlwdD5kAgEPFgIfAAX/ATxzY3JpcHQgc3JjPSJqcXVpLzEuMTEuNC9qcXVlcnktdWktMS4xMS40LmN1c3RvbS5taW4uanMiIHR5cGU9InRleHQvamF2YXNjcmlwdCI+PC9zY3JpcHQ+PGxpbmsgaHJlZj0ianF1aS8xLjExLjQvYmxhY2stdGllL2pxdWVyeS11aS5jc3MiIHJlbD0iU3R5bGVzaGVldCIgY2xhc3M9InVpLXRoZW1lIiAvPjxsaW5rIGhyZWY9ImpxdWkvMS4xMS40L2JsYWNrLXRpZS90aGVtZS5jc3MiIHJlbD0iU3R5bGVzaGVldCIgY2xhc3M9InVpLXRoZW1lIiAvPmQCAQ9kFgQCAw8WAh4FYWxpZ24FBmNlbnRlchYGAgEPFgIeA3NyYwUXfi9pbWFnZXMvQWdlbmN5TmFtZS5naWZkAgMPFgIeCGRpc2FibGVkZBYCZg9kFgRmD2QWAgIBDw8WAh8ABcALICA8YSBjbGFzcz0iTWVudVRleHQgcDJjLW5vd3JhcCIgaHJlZj0iLi9tYWluLmFzcHgiPkhPTUU8L2E+PHNwYW4gY2xhc3M9Ik1lbnVUZXh0Ij4mbmJzcDsmbmJzcDsmbmJzcDsmbmJzcDs8L3NwYW4+ICA8YSBjbGFzcz0iTWVudVRleHQgcDJjLW5vd3JhcCIgaHJlZj0iLi9zdW1tYXJ5LmFzcHgiPkVWRU5UIFNFQVJDSDwvYT48c3BhbiBjbGFzcz0iTWVudVRleHQiPiZuYnNwOyZuYnNwOyZuYnNwOyZuYnNwOzwvc3Bhbj4gIDxhIGNsYXNzPSJNZW51VGV4dCBwMmMtbm93cmFwIiBocmVmPSIuL2NvbW11bml0eWNhbGVuZGFyLmFzcHgiPkNPTU1VTklUWSBDQUxFTkRBUjwvYT48c3BhbiBjbGFzcz0iTWVudVRleHQiPiZuYnNwOyZuYnNwOyZuYnNwOyZuYnNwOzwvc3Bhbj4gIDxhIGNsYXNzPSJNZW51VGV4dCBwMmMtbm93cmFwIiBocmVmPSIuL21vc3R3YW50ZWQuYXNweCI+TU9TVCBXQU5URUQ8L2E+PHNwYW4gY2xhc3M9Ik1lbnVUZXh0Ij4mbmJzcDsmbmJzcDsmbmJzcDsmbmJzcDs8L3NwYW4+ICA8YSBjbGFzcz0iTWVudVRleHQgcDJjLW5vd3JhcCIgaHJlZj0iLi9kYWlseWJ1bGxldGluLmFzcHgiPkRBSUxZIEJVTExFVElOPC9hPjxzcGFuIGNsYXNzPSJNZW51VGV4dCI+Jm5ic3A7Jm5ic3A7Jm5ic3A7Jm5ic3A7PC9zcGFuPiAgPGEgY2xhc3M9Ik1lbnVUZXh0IHAyYy1ub3dyYXAiIGhyZWY9Ii4vYXJyZXN0cy5hc3B4Ij5BUlJFU1RTPC9hPjxzcGFuIGNsYXNzPSJNZW51VGV4dCI+Jm5ic3A7Jm5ic3A7Jm5ic3A7Jm5ic3A7PC9zcGFuPiAgPGEgY2xhc3M9Ik1lbnVUZXh0IHAyYy1ub3dyYXAiIGhyZWY9Ii4vY29udGFjdC5hc3B4Ij5DT05UQUNUIFVTPC9hPjxzcGFuIGNsYXNzPSJNZW51VGV4dCI+Jm5ic3A7Jm5ic3A7Jm5ic3A7Jm5ic3A7PC9zcGFuPiAgPGEgY2xhc3M9Ik1lbnVUZXh0IHAyYy1ub3dyYXAiIGhyZWY9Ii4vZmFxLmFzcHgiPkZBUTwvYT48c3BhbiBjbGFzcz0iTWVudVRleHQiPiZuYnNwOyZuYnNwOyZuYnNwOyZuYnNwOzwvc3Bhbj4gIDxhIGNsYXNzPSJNZW51VGV4dCBwMmMtbm93cmFwIiBocmVmPSIuL3dhbnRlZGxpc3QuYXNweCI+V0FOVEVEIExJU1Q8L2E+PHNwYW4gY2xhc3M9Ik1lbnVUZXh0Ij4mbmJzcDsmbmJzcDsmbmJzcDsmbmJzcDs8L3NwYW4+ICA8YSBjbGFzcz0iTWVudVRleHQgcDJjLW5vd3JhcCIgaHJlZj0iLi9qYWlsaW5tYXRlcy5hc3B4Ij5JTk1BVEUgSU5RVUlSWTwvYT48c3BhbiBjbGFzcz0iTWVudVRleHQiPiZuYnNwOyZuYnNwOyZuYnNwOyZuYnNwOzwvc3Bhbj4gIDxhIGNsYXNzPSJNZW51VGV4dCBwMmMtbm93cmFwIiBocmVmPSIuL3NleG9mZmVuZGVycy5hc3B4Ij5TRVggT0ZGRU5ERVJTPC9hPjxzcGFuIGNsYXNzPSJNZW51VGV4dCI+Jm5ic3A7Jm5ic3A7Jm5ic3A7Jm5ic3A7PC9zcGFuPiAgPGEgY2xhc3M9Ik1lbnVUZXh0IHAyYy1ub3dyYXAiIGhyZWY9Ii4vU2V4T2ZmZW5kZXJTZWFyY2guYXNweCI+U0VYIE9GRkVOREVSIFNFQVJDSDwvYT5kZAIBD2QWAgIBD2QWAmYPEA8WBh4NRGF0YVRleHRGaWVsZAUEdGV4dB4ORGF0YVZhbHVlRmllbGQFBGxpbmseC18hRGF0YUJvdW5kZ2QQFQ0QLSBRdWljayBMaW5rcyAtIARIb21lDEV2ZW50IFNlYXJjaBJDb21tdW5pdHkgQ2FsZW5kYXILTW9zdCBXYW50ZWQHQXJyZXN0cw5EYWlseSBCdWxsZXRpbgpDb250YWN0IFVzA0ZBUQtXYW50ZWQgTGlzdA5Jbm1hdGUgSW5xdWlyeQ1TZXggT2ZmZW5kZXJzE1NleCBPZmZlbmRlciBTZWFyY2gVDQN+LzALfi9tYWluLmFzcHgOfi9zdW1tYXJ5LmFzcHgYfi9jb21tdW5pdHljYWxlbmRhci5hc3B4EX4vbW9zdHdhbnRlZC5hc3B4Dn4vYXJyZXN0cy5hc3B4FH4vZGFpbHlidWxsZXRpbi5hc3B4Dn4vY29udGFjdC5hc3B4Cn4vZmFxLmFzcHgRfi93YW50ZWRsaXN0LmFzcHgSfi9qYWlsaW5tYXRlcy5hc3B4E34vc2V4b2ZmZW5kZXJzLmFzcHgYfi9TZXhPZmZlbmRlclNlYXJjaC5hc3B4FCsDDWdnZ2dnZ2dnZ2dnZ2cWAWZkAgcPZBYCZg9kFgICAw8PFgIfAAUqVGhlcmUgYXJlIGN1cnJlbnRseSBubyBpdGVtcyBpbiB5b3VyIGNhcnQuZGQCBw9kFgYCAQ9kFgYCAQ9kFgJmD2QWBGYPD2QWBB4Fc3R5bGUFGVRFWFQtVFJBTlNGT1JNOnVwcGVyY2FzZTseCG9uY2hhbmdlBTFpZihWYWxpZGF0ZUNhc2VOdW1iZXIodGhpcyk9PWZhbHNlKSByZXR1cm4gZmFsc2U7ZAICD2QWAgIBDw9kFgQfBwUZVEVYVC1UUkFOU0ZPUk06dXBwZXJjYXNlOx8IBTFpZihWYWxpZGF0ZUNhc2VOdW1iZXIodGhpcyk9PWZhbHNlKSByZXR1cm4gZmFsc2U7ZAIDD2QWAmYPZBYCAgsPFgIeBnR5cGVObwUBM2QCBQ9kFgJmD2QWAgILDxYCHwkFATRkAgUPZBYCAgMPPCsACwEADxYIHghEYXRhS2V5cxYAHgtfIUl0ZW1Db3VudAIKHglQYWdlQ291bnQCXh4VXyFEYXRhU291cmNlSXRlbUNvdW50AqUHZBYCZg9kFhQCAg9kFgpmDw8WAh8ABQY2NzQ4NDRkZAIBDw8WAh8ABRtBQkFURSwgUk9NQU4gVkVETyAoVyAvTS8zOClkZAICDw8WAh8ABQ5JREVOVElUWSBUSEVGVGRkAgMPDxYCHwAFCjA5LzIxLzIwMThkZAIEDw8WAh8ABR5HdWlsZm9yZCBDb3VudHkgU2hlcmlmZiBPZmZpY2VkZAIDD2QWCmYPDxYCHwAFBjY4Nzg4NWRkAgEPDxYCHwAFH0FEQU1TLCBBRFJJQU4gUVVJTlRFTCAoQiAvTS8yNylkZAICDw8WAh8ABRlGQUlMVVJFIFRPIEFQUEVBUiBPTiBNSVNEZGQCAw8PFgIfAAUKMDEvMzEvMjAxOWRkAgQPDxYCHwAFHkd1aWxmb3JkIENvdW50eSBTaGVyaWZmIE9mZmljZWRkAgQPZBYKZg8PFgIfAAUGNjg0OTU3ZGQCAQ8PFgIfAAUiQURBTVMsIERFTk5JUyBDQU1QSVRFTExJIChXIC9NLzMyKWRkAgIPDxYCHwAFHFBST0JBVElPTiBWSU9MQVRJT04gKEZFTE9OWSlkZAIDDw8WAh8ABQowMS8xMy8yMDE5ZGQCBA8PFgIfAAUeR3VpbGZvcmQgQ291bnR5IFNoZXJpZmYgT2ZmaWNlZGQCBQ9kFgpmDw8WAh8ABQY2ODY0MTVkZAIBDw8WAh8ABR9BREVSSE9MRCwgQlJBRCBEQU5JRUwgKFcgL00vMzgpZGQCAg8PFgIfAAUcUFJPQkFUSU9OIFZJT0xBVElPTiAoRkVMT05ZKWRkAgMPDxYCHwAFCjAxLzIyLzIwMTlkZAIEDw8WAh8ABR5HdWlsZm9yZCBDb3VudHkgU2hlcmlmZiBPZmZpY2VkZAIGD2QWCmYPDxYCHwAFBjY4NTA5MmRkAgEPDxYCHwAFJEFERVJPVU5NVSwgR0lERU9OIEFCRURPVFVOIChCIC9NLzI4KWRkAgIPDxYCHwAFHFBST0JBVElPTiBWSU9MQVRJT04gKEZFTE9OWSlkZAIDDw8WAh8ABQowMS8xNi8yMDE5ZGQCBA8PFgIfAAUeR3VpbGZvcmQgQ291bnR5IFNoZXJpZmYgT2ZmaWNlZGQCBw9kFgpmDw8WAh8ABQY2ODY1NjJkZAIBDw8WAh8ABRxBREtJTlMsIExJU0EgTUFSSUUgKFcgL0YvMzIpZGQCAg8PFgIfAAUcUFJPQkFUSU9OIFZJT0xBVElPTiAoRkVMT05ZKWRkAgMPDxYCHwAFCjAxLzI1LzIwMTlkZAIEDw8WAh8ABR5HdWlsZm9yZCBDb3VudHkgU2hlcmlmZiBPZmZpY2VkZAIID2QWCmYPDxYCHwAFBjY4NDcxMGRkAgEPDxYCHwAFH0FHVUlMQVIsIEpFU1VTIEFMRU1BTiAoVyAvTS81NylkZAICDw8WAh8ABRFBU1NBVUxUIE9OIEZFTUFMRWRkAgMPDxYCHwAFCjAxLzA4LzIwMTlkZAIEDw8WAh8ABR5HdWlsZm9yZCBDb3VudHkgU2hlcmlmZiBPZmZpY2VkZAIJD2QWCmYPDxYCHwAFBjY3MzgwOWRkAgEPDxYCHwAFJUFHVUlMQVItVkVMQVNRVUVaLCBST0JFUlRPICAoVyAvTS8yNClkZAICDw8WAh8ABQtJTU1JR1JBVElPTmRkAgMPDxYCHwAFCjA4LzI5LzIwMThkZAIEDw8WAh8ABR5HdWlsZm9yZCBDb3VudHkgU2hlcmlmZiBPZmZpY2VkZAIKD2QWCmYPDxYCHwAFBjY4NjM4MmRkAgEPDxYCHwAFIEFMQlJJR0hULCBCUkFORE9OIFJFSUQgKFcgL00vMzYpZGQCAg8PFgIfAAUEV1JJVGRkAgMPDxYCHwAFCjAxLzIyLzIwMTlkZAIEDw8WAh8ABR5HdWlsZm9yZCBDb3VudHkgU2hlcmlmZiBPZmZpY2VkZAILD2QWCmYPDxYCHwAFBjY4MzkxN2RkAgEPDxYCHwAFIEFMRFJJREdFLCBKT1NIVUEgU0hBTkUgKFcgL00vMjkpZGQCAg8PFgIfAAUVTEFSQ0VOWSAtIE1JU0RFTUVBTk9SZGQCAw8PFgIfAAUKMTIvMjgvMjAxOGRkAgQPDxYCHwAFHkd1aWxmb3JkIENvdW50eSBTaGVyaWZmIE9mZmljZWRkAgkPZBYEAgEPZBYCZg9kFgICDA8WAh8JBQExZAIDD2QWAmYPZBYCAgMPFCsAAg8WBB8GZx8LAglkZBYCZg9kFhICAQ9kFgJmDxUCBGV2ZW4AZAICD2QWAmYPFQIDb2RkMTxiPkFSUkVTVDwvYj4tICA8aT4xKSBGYWlsdXJlIFRvIEFwcGVhciBPbi4uLjwvST5kAgMPZBYCZg8VAgRldmVuJyBhdCA1MDAwLUJMSyBOYyAxNTAgRS9vbGQgUmVpZHN2aWxsZSBSZGQCBA9kFgJmDxUCA29kZABkAgUPZBYCZg8VAgRldmVuAGQCBg9kFgJmDxUCA29kZABkAgcPZBYCZg8VAgRldmVuAGQCCA9kFgJmDxUCA29kZABkAgkPZBYCZg8VAgRldmVuAGQCAg8WAh8AZWQYAgUeX19Db250cm9sc1JlcXVpcmVQb3N0QmFja0tleV9fFgEFQ2N0bDAwJE1hc3RlclBhZ2UkbWFpbkNvbnRlbnQkUmlnaHRDb2x1bW5Db250ZW50JGN0bDAyJEJJbWFnZUJ1dHRvbjEFPmN0bDAwJE1hc3RlclBhZ2UkbWFpbkNvbnRlbnQkUmlnaHRDb2x1bW5Db250ZW50JGN0bDAxJGx2RXZlbnRzDxQrAA5kZGRkZGRkPCsACQACCWRkZGYC/////w9k3mRo5Fl/I5DZzg/ndINLI0jpjM9VxAQfx13fLdcd5LY=',
                             '__VIEWSTATEGENERATOR': '5B295459',
                             'ctl00$MasterPage$mainContent$CenterColumnContent$btnInmateDetail': '',
                             'ctl00$MasterPage$mainContent$CenterColumnContent$hfRecordIndex': '233'},
               'response_type': 'html',
               'task_type': 2},
 'scrape_type': 'background',
 'scraper_start_time': '2019-02-04T02:00:49.643411'}
```

**Comment by jamwalla** [comment]
This codepath is gone now, but I'm not sure how this could have occurred - it looks like we called `normalize` on an empty string from the old enum_overrides dict. Reopen this if i'm missing something, though!
