### ISSUE TITLE
us_ms_desoto key errors

### ISSUE THREAD

**Issue by colincadams** [Recidiviz/recidiviz-data#840]
## 'DOC' in BondType

```
Traceback (most recent call last):
  File "/app/recidiviz/common/constants/mappable_enum.py", line 77, in _parse_to_enum
    return complete_map[label]
KeyError: 'DOC'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/recidiviz/ingest/worker.py", line 102, in work
    result = scraper_task(params)
  File "/app/recidiviz/ingest/base_scraper.py", line 233, in _generic_scrape
    scraped_data.ingest_info), metadata)
  File "/app/recidiviz/persistence/persistence.py", line 151, in write
    people = converter.convert(ingest_info, metadata)
  File "/app/recidiviz/persistence/converter/converter.py", line 35, in convert
    return _Converter(ingest_info, metadata).convert()
  File "/app/recidiviz/persistence/converter/converter.py", line 53, in convert
    return [self._convert_person(p) for p in self.ingest_info.people]
  File "/app/recidiviz/persistence/converter/converter.py", line 53, in <listcomp>
    return [self._convert_person(p) for p in self.ingest_info.people]
  File "/app/recidiviz/persistence/converter/converter.py", line 64, in _convert_person
    for booking_id in ingest_person.booking_ids
  File "/app/recidiviz/persistence/converter/converter.py", line 64, in <listcomp>
    for booking_id in ingest_person.booking_ids
  File "/app/recidiviz/persistence/converter/converter.py", line 85, in _convert_booking
    charges = self._convert_charges(ingest_charges)
  File "/app/recidiviz/persistence/converter/converter.py", line 108, in _convert_charges
    new_charge = self._convert_charge(ingest_charge)
  File "/app/recidiviz/persistence/converter/converter.py", line 125, in _convert_charge
    ingest_charge)
  File "/app/recidiviz/persistence/converter/converter_utils.py", line 41, in fn
    return func(getattr(proto, field_name))
  File "/app/recidiviz/persistence/converter/converter.py", line 123, in <lambda>
    fn(lambda i: bond.convert(self.bonds[i], self.metadata),
  File "/app/recidiviz/persistence/converter/bond.py", line 39, in convert
    metadata.enum_overrides, default=inferred_bond_type)
  File "/app/recidiviz/persistence/converter/converter_utils.py", line 42, in fn
    return func(getattr(proto, field_name), *additional_func_args)
  File "/app/recidiviz/common/constants/mappable_enum.py", line 57, in parse
    return cls._parse_to_enum(label, complete_map)
  File "/app/recidiviz/common/constants/mappable_enum.py", line 79, in _parse_to_enum
    raise EnumParsingError(cls, label)
recidiviz.common.constants.mappable_enum.EnumParsingError: Could not parse DOC when building <enum 'BondType'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/recidiviz/utils/auth.py", line 98, in auth_and_call
    return func(*args, **kwargs)
  File "/app/recidiviz/ingest/worker.py", line 109, in work
    raise RequestProcessingError(region, task, params)
recidiviz.ingest.worker.RequestProcessingError: Error when running '_generic_scrape' for 'us_ms_desoto' with request:
{'ingest_info': None,
 'next_task': {'content': None,
               'cookies': {'ASP.NET_SessionId': 'v0fouxs4rcwwajau0pscuppz',
                           'inmates_aspx_gvInmates': 'page1%7csize100%7cconditions1%7c0%7c3%7chierarchy10%7c0%7c-1%7c1%7c-1%7c2%7c-1%7c3%7c-1%7c4%7c-1%7c5%7c-1%7c6%7c-1%7c7%7c-1%7c8%7c-1%7c9%7c-1%7cvisible10%7ct0%7cf1%7cf2%7cf3%7ct4%7ct5%7ct6%7ct7%7cf8%7cf9%7cwidth10%7c150px%7c50px%7c50px%7c65px%7c20px%7c25px%7c20px%7c40px%7c60px%7c150px'},
               'custom': {},
               'endpoint': 'https://jail.desotosheriff.org/DCN/inmate-details?id=LadjjNUU3zo%253d&bid=47%252bYzWsfcRA%253d',
               'headers': None,
               'json': None,
               'post_data': None,
               'response_type': 'html',
               'task_type': 2},
 'scrape_type': 'background',
 'scraper_start_time': '2019-02-05T03:00:10.561053'}
```

**Comment by colincadams** [comment]
## 'COUNTY JAIL TIME' in BondType

```
Traceback (most recent call last):
  File "/app/recidiviz/common/constants/mappable_enum.py", line 77, in _parse_to_enum
    return complete_map[label]
KeyError: 'COUNTY JAIL TIME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/recidiviz/ingest/worker.py", line 102, in work
    result = scraper_task(params)
  File "/app/recidiviz/ingest/base_scraper.py", line 233, in _generic_scrape
    scraped_data.ingest_info), metadata)
  File "/app/recidiviz/persistence/persistence.py", line 151, in write
    people = converter.convert(ingest_info, metadata)
  File "/app/recidiviz/persistence/converter/converter.py", line 35, in convert
    return _Converter(ingest_info, metadata).convert()
  File "/app/recidiviz/persistence/converter/converter.py", line 53, in convert
    return [self._convert_person(p) for p in self.ingest_info.people]
  File "/app/recidiviz/persistence/converter/converter.py", line 53, in <listcomp>
    return [self._convert_person(p) for p in self.ingest_info.people]
  File "/app/recidiviz/persistence/converter/converter.py", line 64, in _convert_person
    for booking_id in ingest_person.booking_ids
  File "/app/recidiviz/persistence/converter/converter.py", line 64, in <listcomp>
    for booking_id in ingest_person.booking_ids
  File "/app/recidiviz/persistence/converter/converter.py", line 85, in _convert_booking
    charges = self._convert_charges(ingest_charges)
  File "/app/recidiviz/persistence/converter/converter.py", line 108, in _convert_charges
    new_charge = self._convert_charge(ingest_charge)
  File "/app/recidiviz/persistence/converter/converter.py", line 125, in _convert_charge
    ingest_charge)
  File "/app/recidiviz/persistence/converter/converter_utils.py", line 41, in fn
    return func(getattr(proto, field_name))
  File "/app/recidiviz/persistence/converter/converter.py", line 123, in <lambda>
    fn(lambda i: bond.convert(self.bonds[i], self.metadata),
  File "/app/recidiviz/persistence/converter/bond.py", line 39, in convert
    metadata.enum_overrides, default=inferred_bond_type)
  File "/app/recidiviz/persistence/converter/converter_utils.py", line 42, in fn
    return func(getattr(proto, field_name), *additional_func_args)
  File "/app/recidiviz/common/constants/mappable_enum.py", line 57, in parse
    return cls._parse_to_enum(label, complete_map)
  File "/app/recidiviz/common/constants/mappable_enum.py", line 79, in _parse_to_enum
    raise EnumParsingError(cls, label)
recidiviz.common.constants.mappable_enum.EnumParsingError: Could not parse COUNTY JAIL TIME when building <enum 'BondType'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/recidiviz/utils/auth.py", line 98, in auth_and_call
    return func(*args, **kwargs)
  File "/app/recidiviz/ingest/worker.py", line 109, in work
    raise RequestProcessingError(region, task, params)
recidiviz.ingest.worker.RequestProcessingError: Error when running '_generic_scrape' for 'us_ms_desoto' with request:
{'ingest_info': None,
 'next_task': {'content': None,
               'cookies': {'ASP.NET_SessionId': 'v0fouxs4rcwwajau0pscuppz',
                           'inmates_aspx_gvInmates': 'page1%7csize100%7cconditions1%7c0%7c3%7chierarchy10%7c0%7c-1%7c1%7c-1%7c2%7c-1%7c3%7c-1%7c4%7c-1%7c5%7c-1%7c6%7c-1%7c7%7c-1%7c8%7c-1%7c9%7c-1%7cvisible10%7ct0%7cf1%7cf2%7cf3%7ct4%7ct5%7ct6%7ct7%7cf8%7cf9%7cwidth10%7c150px%7c50px%7c50px%7c65px%7c20px%7c25px%7c20px%7c40px%7c60px%7c150px'},
               'custom': {},
               'endpoint': 'https://jail.desotosheriff.org/DCN/inmate-details?id=A1MqsCBlwBI%253d&bid=NTrgp2sl3Og%253d',
               'headers': None,
               'json': None,
               'post_data': None,
               'response_type': 'html',
               'task_type': 2},
 'scrape_type': 'background',
 'scraper_start_time': '2019-02-05T03:00:10.561053'}
```

**Comment by colincadams** [comment]
## 'M' in Race

```
Traceback (most recent call last):
  File "/app/recidiviz/common/constants/mappable_enum.py", line 77, in _parse_to_enum
    return complete_map[label]
KeyError: 'M'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/recidiviz/ingest/worker.py", line 102, in work
    result = scraper_task(params)
  File "/app/recidiviz/ingest/base_scraper.py", line 233, in _generic_scrape
    scraped_data.ingest_info), metadata)
  File "/app/recidiviz/persistence/persistence.py", line 151, in write
    people = converter.convert(ingest_info, metadata)
  File "/app/recidiviz/persistence/converter/converter.py", line 35, in convert
    return _Converter(ingest_info, metadata).convert()
  File "/app/recidiviz/persistence/converter/converter.py", line 53, in convert
    return [self._convert_person(p) for p in self.ingest_info.people]
  File "/app/recidiviz/persistence/converter/converter.py", line 53, in <listcomp>
    return [self._convert_person(p) for p in self.ingest_info.people]
  File "/app/recidiviz/persistence/converter/converter.py", line 60, in _convert_person
    person_builder, ingest_person, self.metadata)
  File "/app/recidiviz/persistence/converter/person.py", line 41, in copy_fields_to_builder
    metadata.enum_overrides)
  File "/app/recidiviz/persistence/converter/person.py", line 100, in _parse_race_and_ethnicity
    race = fn(Race.parse, 'race', proto, enum_overrides)
  File "/app/recidiviz/persistence/converter/converter_utils.py", line 42, in fn
    return func(getattr(proto, field_name), *additional_func_args)
  File "/app/recidiviz/common/constants/mappable_enum.py", line 46, in parse
    return cls._parse_to_enum(label, cls._get_default_map())
  File "/app/recidiviz/common/constants/mappable_enum.py", line 79, in _parse_to_enum
    raise EnumParsingError(cls, label)
recidiviz.common.constants.mappable_enum.EnumParsingError: Could not parse M when building <enum 'Race'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/recidiviz/utils/auth.py", line 98, in auth_and_call
    return func(*args, **kwargs)
  File "/app/recidiviz/ingest/worker.py", line 109, in work
    raise RequestProcessingError(region, task, params)
recidiviz.ingest.worker.RequestProcessingError: Error when running '_generic_scrape' for 'us_mo_stone' with request:
{'ingest_info': None,
 'next_task': {'content': None,
               'cookies': {'PHPSESSID': '302820f55e0c7cfb94bef1789dc86836'},
               'custom': {},
               'endpoint': 'https://www.stonecountymosheriff.com/roster_view.php?booking_num=19-012001',
               'headers': None,
               'json': None,
               'post_data': None,
               'response_type': 'html',
               'task_type': 2},
 'scrape_type': 'background',
 'scraper_start_time': '2019-02-05T03:00:27.508616'}
```

**Comment by colincadams** [comment]
## 'OTHER' in BondType

```
Traceback (most recent call last):
  File "/app/recidiviz/common/constants/mappable_enum.py", line 77, in _parse_to_enum
    return complete_map[label]
KeyError: 'OTHER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/recidiviz/ingest/worker.py", line 102, in work
    result = scraper_task(params)
  File "/app/recidiviz/ingest/base_scraper.py", line 233, in _generic_scrape
    scraped_data.ingest_info), metadata)
  File "/app/recidiviz/persistence/persistence.py", line 151, in write
    people = converter.convert(ingest_info, metadata)
  File "/app/recidiviz/persistence/converter/converter.py", line 35, in convert
    return _Converter(ingest_info, metadata).convert()
  File "/app/recidiviz/persistence/converter/converter.py", line 53, in convert
    return [self._convert_person(p) for p in self.ingest_info.people]
  File "/app/recidiviz/persistence/converter/converter.py", line 53, in <listcomp>
    return [self._convert_person(p) for p in self.ingest_info.people]
  File "/app/recidiviz/persistence/converter/converter.py", line 64, in _convert_person
    for booking_id in ingest_person.booking_ids
  File "/app/recidiviz/persistence/converter/converter.py", line 64, in <listcomp>
    for booking_id in ingest_person.booking_ids
  File "/app/recidiviz/persistence/converter/converter.py", line 85, in _convert_booking
    charges = self._convert_charges(ingest_charges)
  File "/app/recidiviz/persistence/converter/converter.py", line 108, in _convert_charges
    new_charge = self._convert_charge(ingest_charge)
  File "/app/recidiviz/persistence/converter/converter.py", line 125, in _convert_charge
    ingest_charge)
  File "/app/recidiviz/persistence/converter/converter_utils.py", line 41, in fn
    return func(getattr(proto, field_name))
  File "/app/recidiviz/persistence/converter/converter.py", line 123, in <lambda>
    fn(lambda i: bond.convert(self.bonds[i], self.metadata),
  File "/app/recidiviz/persistence/converter/bond.py", line 39, in convert
    metadata.enum_overrides, default=inferred_bond_type)
  File "/app/recidiviz/persistence/converter/converter_utils.py", line 42, in fn
    return func(getattr(proto, field_name), *additional_func_args)
  File "/app/recidiviz/common/constants/mappable_enum.py", line 57, in parse
    return cls._parse_to_enum(label, complete_map)
  File "/app/recidiviz/common/constants/mappable_enum.py", line 79, in _parse_to_enum
    raise EnumParsingError(cls, label)
recidiviz.common.constants.mappable_enum.EnumParsingError: Could not parse OTHER when building <enum 'BondType'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/recidiviz/utils/auth.py", line 98, in auth_and_call
    return func(*args, **kwargs)
  File "/app/recidiviz/ingest/worker.py", line 109, in work
    raise RequestProcessingError(region, task, params)
recidiviz.ingest.worker.RequestProcessingError: Error when running '_generic_scrape' for 'us_ms_desoto' with request:
{'ingest_info': None,
 'next_task': {'content': None,
               'cookies': {'ASP.NET_SessionId': 'v0fouxs4rcwwajau0pscuppz',
                           'inmates_aspx_gvInmates': 'page1%7csize100%7cconditions1%7c0%7c3%7chierarchy10%7c0%7c-1%7c1%7c-1%7c2%7c-1%7c3%7c-1%7c4%7c-1%7c5%7c-1%7c6%7c-1%7c7%7c-1%7c8%7c-1%7c9%7c-1%7cvisible10%7ct0%7cf1%7cf2%7cf3%7ct4%7ct5%7ct6%7ct7%7cf8%7cf9%7cwidth10%7c150px%7c50px%7c50px%7c65px%7c20px%7c25px%7c20px%7c40px%7c60px%7c150px'},
               'custom': {},
               'endpoint': 'https://jail.desotosheriff.org/DCN/inmate-details?id=40GZ1OxbqAE%253d&bid=jC4ndXZdIU8%253d',
               'headers': None,
               'json': None,
               'post_data': None,
               'response_type': 'html',
               'task_type': 2},
 'scrape_type': 'background',
 'scraper_start_time': '2019-02-05T03:00:10.561053'}
```
