### ISSUE TITLE
us_ar_van_buren / data convert: cannot parse dollar value 'NONE'

### ISSUE THREAD

**Issue by colincadams** [Recidiviz/recidiviz-data#865]
https://pantheon.corp.google.com/errors/CNHbrrTd7-KD6AE?time=P1D&project=recidiviz-123

```
Traceback (most recent call last):
  File "/app/recidiviz/persistence/converter/converter_utils.py", line 175, in parse_dollars
    return int(locale.atof(clean_string))
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/locale.py", line 326, in atof
    return func(delocalize(string))
ValueError: could not convert string to float: 'NONE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/recidiviz/ingest/worker.py", line 102, in work
    result = scraper_task(params)
  File "/app/recidiviz/ingest/scrape/base_scraper.py", line 234, in _generic_scrape
    scraped_data.ingest_info), metadata)
  File "/app/recidiviz/persistence/persistence.py", line 151, in write
    people = converter.convert(ingest_info, metadata)
  File "/app/recidiviz/persistence/converter/converter.py", line 35, in convert
    return _Converter(ingest_info, metadata).convert()
  File "/app/recidiviz/persistence/converter/converter.py", line 53, in convert
    return [self._convert_person(p) for p in self.ingest_info.people]
  File "/app/recidiviz/persistence/converter/converter.py", line 53, in <listcomp>
    return [self._convert_person(p) for p in self.ingest_info.people]
  File "/app/recidiviz/persistence/converter/converter.py", line 64, in _convert_person
    for booking_id in ingest_person.booking_ids
  File "/app/recidiviz/persistence/converter/converter.py", line 64, in <listcomp>
    for booking_id in ingest_person.booking_ids
  File "/app/recidiviz/persistence/converter/converter.py", line 91, in _convert_booking
    ingest_booking)
  File "/app/recidiviz/persistence/converter/converter_utils.py", line 41, in fn
    return func(getattr(proto, field_name))
  File "/app/recidiviz/persistence/converter/converter_utils.py", line 155, in parse_bond_amount_and_check_for_type_and_status_info
    parsed_amount = parse_dollars(amount)
  File "/app/recidiviz/persistence/converter/converter_utils.py", line 177, in parse_dollars
    raise ValueError('cannot parse dollar value: %s' % dollar_string)
ValueError: cannot parse dollar value: NONE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/recidiviz/utils/auth.py", line 98, in auth_and_call
    return func(*args, **kwargs)
  File "/app/recidiviz/ingest/worker.py", line 109, in work
    raise RequestProcessingError(region, task, params)
recidiviz.ingest.worker.RequestProcessingError: Error when running '_generic_scrape' for 'us_ar_van_buren' with request:
{'ingest_info': None,
 'next_task': {'content': None,
               'cookies': {'PHPSESSID': 'ff8de4e74219375cab46d880aa26fc9a'},
               'custom': {},
               'endpoint': 'https://www.vbcso.com/roster_view.php?booking_num=201604872',
               'headers': None,
               'json': None,
               'post_data': None,
               'response_type': 'html',
               'task_type': 2},
 'scrape_type': 'background',
 'scraper_start_time': '2019-02-06T03:00:11.013300'}
```

**Comment by terinpw** [comment]
Fixed with #875
