### ISSUE TITLE
No Documentation on creating "local.yaml"

### ISSUE THREAD

**Issue by jbrambleDC** [Recidiviz/recidiviz-data#94]
#74 mentions adding this file to .gitignore and ensuring it doesn't get uploaded to GAE due to its sensitive nature. 

As it stands currently the README.md in the base directory does not document how to create this, so I get the following error when running locally:
```
webapp2/_internal_error : [Errno 2] No such file or directory: 'local.yaml'
Traceback (most recent call last):
  File "/Users/jordanbramble/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/Users/jordanbramble/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/Users/jordanbramble/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/Users/jordanbramble/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/Users/jordanbramble/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/Users/jordanbramble/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/Users/jordanbramble/recidiviz-data/utils/environment.py", line 91, in check_env
    return func(request_handler, *args, **kwargs)
  File "/Users/jordanbramble/recidiviz-data/utils/auth.py", line 110, in auth_and_call
    return func(request_handler, *args, **kwargs)
  File "/Users/jordanbramble/recidiviz-data/tests/utils/populate_test_db.py", line 170, in get
    load_env_vars()
  File "/Users/jordanbramble/recidiviz-data/tests/utils/populate_test_db.py", line 190, in load_env_vars
    env_vars = environment.load_local_vars()
  File "/Users/jordanbramble/recidiviz-data/utils/environment.py", line 108, in load_local_vars
    with open("local.yaml", 'r') as ymlfile:
  File "/Users/jordanbramble/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/stubs.py", line 285, in __init__
    super(FakeFile, self).__init__(filename, mode, bufsize, **kwargs)
IOError: [Errno 2] No such file or directory: 'local.yaml'
```

**Comment by cawarren** [comment]
Aye.

I'm going to try to keep external documentation relevant to anyone who forks, and Sites pages / internal documentation for Recidiviz team member specific stuff. But this is something that'll need to be there for external folks anyway. Look for a documentation PR shortly.

**Comment by jbrambleDC** [comment]
There is documentation, in #96 awaiting merge. Closing.
